### Load & Combine

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
train=pd.read_csv("train.csv")

In [3]:
test=pd.read_csv("test.csv")

In [4]:
train.shape

(14900, 24)

In [5]:
test.shape

(14900, 24)

In [6]:
train.columns.to_list()

['Employee ID',
 'Age',
 'Gender',
 'Years at Company',
 'Job Role',
 'Monthly Income',
 'Work-Life Balance',
 'Job Satisfaction',
 'Performance Rating',
 'Number of Promotions',
 'Overtime',
 'Distance from Home',
 'Education Level',
 'Marital Status',
 'Number of Dependents',
 'Job Level',
 'Company Size',
 'Company Tenure',
 'Remote Work',
 'Leadership Opportunities',
 'Innovation Opportunities',
 'Company Reputation',
 'Employee Recognition',
 'Attrition']

In [7]:
test.columns.to_list()

['Employee ID',
 'Age',
 'Gender',
 'Years at Company',
 'Job Role',
 'Monthly Income',
 'Work-Life Balance',
 'Job Satisfaction',
 'Performance Rating',
 'Number of Promotions',
 'Overtime',
 'Distance from Home',
 'Education Level',
 'Marital Status',
 'Number of Dependents',
 'Job Level',
 'Company Size',
 'Company Tenure',
 'Remote Work',
 'Leadership Opportunities',
 'Innovation Opportunities',
 'Company Reputation',
 'Employee Recognition',
 'Attrition']

In [8]:
df = pd.concat([train, test], axis=0, ignore_index=True)

### Preprocessing & Cleaning

In [9]:
df.head()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed

In [10]:
df.describe()

,Employee ID,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure
count,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000
mean,37249.500000,38.529746,15.721603,7299.379514,0.832935,49.991584,1.650326,55.727456
std,21505.864514,12.083456,11.223744,2152.508566,0.995289,28.513611,1.553633,25.399349
min,1.000000,18.000000,1.000000,1226.000000,0.000000,1.000000,0.000000,2.000000
25%,18625.250000,28.000000,7.000000,5652.000000,0.000000,25.000000,0.000000,36.000000
50%,37249.500000,39.000000,13.000000,7348.000000,1.000000,50.000000,1.000000,56.000000
75%,55873.750000,49.000000,23.000000,8876.000000,2.000000,75.000000,3.000000,76.000000
max,74498.000000,59.000000,51.000000,16149.000000,4.000000,99.000000,6.000000,128.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74498 entries, 0 to 74497
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Employee ID               74498 non-null  int64
 1   Age                       74498 non-null  int64
 2   Gender                    74498 non-null  object
 3   Years at Company          74498 non-null  int64
 4   Job Role                  74498 non-null  object
 5   Monthly Income            74498 non-null  int64
 6   Work-Life Balance         74498 non-null  object
 7   Job Satisfaction          74498 non-null  object
 8   Performance Rating        74498 non-null  object
 9   Number of Promotions      74498 non-null  int64
 10  Overtime                  74498 non-null  object
 11  Distance from Home        74498 non-null  int64
 12  Education Level           74498 non-null  object
 13  Marital Status            74498 non-null  object
 14  Number of Dependents      74498 non-null  int64
 15  Job Level                 74498 non-null  object
 16  Company Size              74498 non-null  object
 17  Company Tenure            74498 non-null  int64
 18  Remote Work               74498 non-null  object
 19  Leadership Opportunities  74498 non-null  object
 20  Innovation Opportunities  74498 non-null  object
 21  Company Reputation        74498 non-null  object
 22  Employee Recognition      74498 non-null  object
 23  Attrition                 74498 non-null  object
dtypes: int64(8), object(16)
memory usage: 13.6+ MB

In [12]:
df.columns=(
    df.columns
        .str.lower()
        .str.replace(" ", "_")
)

In [13]:
df.columns.to_list()

['employee_id',
 'age',
 'gender',
 'years_at_company',
 'job_role',
 'monthly_income',
 'work-life_balance',
 'job_satisfaction',
 'performance_rating',
 'number_of_promotions',
 'overtime',
 'distance_from_home',
 'education_level',
 'marital_status',
 'number_of_dependents',
 'job_level',
 'company_size',
 'company_tenure',
 'remote_work',
 'leadership_opportunities',
 'innovation_opportunities',
 'company_reputation',
 'employee_recognition',
 'attrition']

In [14]:
df.isnull().sum()

employee_id                 0
age                         0
gender                      0
years_at_company            0
job_role                    0
monthly_income              0
work-life_balance           0
job_satisfaction            0
performance_rating          0
number_of_promotions        0
overtime                    0
distance_from_home          0
education_level             0
marital_status              0
number_of_dependents        0
job_level                   0
company_size                0
company_tenure              0
remote_work                 0
leadership_opportunities    0
innovation_opportunities    0
company_reputation          0
employee_recognition        0
attrition                   0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

### Exploratory Data Analysis (EDA)

In [ ]:
# Does Distance from Home affect attrition

fig = px.box(
    df,
    x="attrition",
    y="distance_from_home",
    color="attrition",
    title="Distance from Home vs Attrition"
)

fig.show()

In [ ]:
#Does Age affect employee attrition?

fig = px.box(
    df,
    x="attrition",
    y="age",
    color="attrition",
    title="Age vs Employee Attrition"
)

fig.show()

In [ ]:
# Does number of promotions affect employee attrition?
promotions_attrition = (
    df.groupby("number_of_promotions")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

left_only = promotions_attrition[promotions_attrition["attrition"] == 1]

fig = px.line(
    left_only,
    x="number_of_promotions",
    y="ratio",
    markers=True,
    title="Dose-Response: Promotions vs Attrition Rate"
)

fig.show()

In [ ]:
# Does Gender affect attrition
gender_attrition = df.groupby("gender")["attrition"].value_counts(normalize=True).reset_index(name="ratio")

fig = px.bar(
    gender_attrition,
    x="gender",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Gender vs Attrition Rate"
)

fig.show()

In [ ]:
# Does Monthly Income affect attrition
fig = px.violin(
    df,
    x="attrition",
    y="monthly_income",
    box=True,
    color="attrition",
    title="Monthly Income vs Attrition"
)

fig.show()

In [ ]:
# Does Monthly Income affect attrition
fig = px.box(
    df,
    x="attrition",
    y="monthly_income",
    color="attrition",
    title="Monthly Income vs Attrition"
)

fig.show()

In [ ]:
# Does Years at Company affect attrition
size_attrition = df.groupby("company_size")["attrition"].value_counts(normalize=True).reset_index(name="ratio")

fig = px.bar(
    size_attrition,
    x="company_size",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Company Size vs Attrition"
)

fig.show()

In [ ]:
remote = (
    df.groupby("remote_work")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.bar(
    remote,
    x="remote_work",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Remote Work vs Attrition Rate"
)

fig.show()

In [ ]:
# Who leaves the company the most

ct = pd.crosstab(df["job_role"], df["attrition"], normalize="index")

fig = px.imshow(
    ct,
    text_auto=True,
    title="Attrition Rate by Job Role"
)

fig.show()

In [ ]:
# Do Work-Life Balance and Remote Work affect attrition
wlb = df.groupby("work-life_balance")["attrition"].value_counts(normalize=True).reset_index(name="ratio")

fig = px.bar(
    wlb,
    x="work-life_balance",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Work-Life Balance vs Attrition"
)

fig.show()

In [ ]:
poor_fair = df[df["work-life_balance"].isin(["Poor", "Fair"])]

pd.crosstab(
    poor_fair["overtime"],
    poor_fair["attrition"],
    normalize="index"
)

In [ ]:
poor_fair = df[df["work-life_balance"].isin(["Poor", "Fair"])]

satisfaction = (
    poor_fair.groupby("job_satisfaction")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.bar(
    satisfaction,
    x="job_satisfaction",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Job Satisfaction vs Attrition (Poor/Fair Work-Life Balance)"
)

fig.show()

In [ ]:
recognition = (
    poor_fair.groupby("employee_recognition")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.bar(
    recognition,
    x="employee_recognition",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Employee Recognition vs Attrition"
)

fig.show()

In [ ]:
leadership = (
    poor_fair.groupby("leadership_opportunities")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.bar(
    leadership,
    x="leadership_opportunities",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Leadership Opportunities vs Attrition"
)

fig.show()

In [ ]:
reputation = (
    poor_fair.groupby("company_reputation")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.bar(
    reputation,
    x="company_reputation",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Company Reputation vs Attrition"
)

fig.show()

In [ ]:
recognition = (
    df.groupby("employee_recognition")["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.bar(
    recognition,
    x="employee_recognition",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Employee Recognition vs Attrition"
)

fig.show()

In [ ]:
df["attrition"] = df["attrition"].map({
    "Stayed": 0,
    "Left": 1
})
numeric_df = df.select_dtypes(include=["int64"])
corr = numeric_df.corr()

plt.figure(figsize=(12,8))
sns.heatmap(corr, annot=False, cmap="coolwarm", center=0)
plt.title("Correlation Heatmap")
plt.show()

In [ ]:
high_risk = df[
    (df["remote_work"] == "No") &
    (df["distance_from_home"] > df["distance_from_home"].median()) &
    (df["work-life_balance"].isin(["Poor", "Fair"])) &
    (df["number_of_promotions"] == 0)
]

risk = (
    high_risk["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.pie(
    risk,
    names="attrition",
    values="ratio",
    title="High Risk Group Attrition Distribution"
)

fig.show()

In [ ]:
low_risk = df[
    (df["remote_work"] == "Yes") &
    (df["distance_from_home"] <= df["distance_from_home"].median()) &
    (df["work-life_balance"].isin(["Good", "Excellent"])) &
    (df["number_of_promotions"] > 0)
]

risk = (
    low_risk["attrition"]
    .value_counts(normalize=True)
    .reset_index(name="ratio")
)

fig = px.pie(
    risk,
    names="attrition",
    values="ratio",
    title="Low Risk Group Attrition Distribution"
)

fig.show()

### Visualization

#### Overall Attrition Distribution

In [ ]:
# Who is leaving the company overall
attrition_counts = df["attrition"].value_counts().reset_index()
attrition_counts.columns = ["attrition", "count"]

fig = px.pie(
    attrition_counts,
    names="attrition",
    values="count",
    title="Overall Attrition Distribution"
)

fig.show()

#### Work-Life Balance vs Attrition

In [ ]:
# Does work-life balance affect attrition
wlb = df.groupby("work-life_balance")["attrition"] \
    .value_counts(normalize=True) \
    .reset_index(name="ratio")

fig = px.bar(
    wlb,
    x="work-life_balance",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Work-Life Balance vs Attrition"
)

fig.show()

#### Remote Work Effect

In [ ]:
# Does remote work reduce attrition
remote = df.groupby("remote_work")["attrition"] \
    .value_counts(normalize=True) \
    .reset_index(name="ratio")

fig = px.bar(
    remote,
    x="remote_work",
    y="ratio",
    color="attrition",
    barmode="group",
    title="Remote Work vs Attrition"
)

fig.show()

#### Promotions vs Attrition (Dose Effect)

In [ ]:
# Do promotions reduce attrition
prom = df.groupby("number_of_promotions")["attrition"] \
    .value_counts(normalize=True) \
    .reset_index(name="ratio")

left_only = prom[prom["attrition"] == 1]

fig = px.line(
    left_only,
    x="number_of_promotions",
    y="ratio",
    markers=True,
    title="Promotions vs Attrition Rate"
)

fig.show()

#### Distance from Home vs Attrition

In [ ]:
# Does distance affect attrition
fig = px.box(
    df,
    x="attrition",
    y="distance_from_home",
    color="attrition",
    title="Distance from Home vs Attrition"
)

fig.show()

#### High Risk vs Low Risk

In [ ]:
# What happens when multiple risk factors combine
high_risk = df[
    (df["remote_work"] == "No") &
    (df["distance_from_home"] > df["distance_from_home"].median()) &
    (df["work-life_balance"].isin(["Poor", "Fair"])) &
    (df["number_of_promotions"] == 0)
]

risk = high_risk["attrition"].value_counts(normalize=True).reset_index(name="ratio")

fig = px.pie(
    risk,
    names="attrition",
    values="ratio",
    title="High Risk Group Attrition"
)

fig.show()

In [ ]:
low_risk = df[
    (df["remote_work"] == "Yes") &
    (df["distance_from_home"] <= df["distance_from_home"].median()) &
    (df["work-life_balance"].isin(["Good", "Excellent"])) &
    (df["number_of_promotions"] > 0)
]

risk2 = low_risk["attrition"].value_counts(normalize=True).reset_index(name="ratio")

fig = px.pie(
    risk2,
    names="attrition",
    values="ratio",
    title="Low Risk Group Attrition"
)

fig.show()

In [ ]:
df.to_csv("data.csv", index=False)